/* config.java (config.java.in) */
/* (c) Guido Scholz */
/* This file is generated by 'config.status'. It contains static variables, */
/* which are defined by ./configure (have a look at configure.ac) */

public class Config 
{
    private Config()
    {
    }
/*    public final static String ICONDIR = "/usr/local/share/pixmaps";*/
    public final static String HTMLDIR = "/usr/local/share/doc/jtrain/html";
}

